<?php

namespace AppBundle\Repository;

/**
 * appRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class appRepository extends \Doctrine\ORM\EntityRepository
{
}
