<?php

namespace AppBundle\Repository;

/**
 * statusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class statusRepository extends \Doctrine\ORM\EntityRepository
{
}
